# Generated by Django 2.2.16 on 2022-08-18 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Course name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Course created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Course updated at')),
                ('owner_id', models.IntegerField(null=True, verbose_name='Course creator id')),
                ('owner_name', models.CharField(max_length=50, null=True, verbose_name='Course creator name')),
                ('thumb_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='Course thumb cover url')),
                ('cover_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='Course cover url')),
                ('description', models.CharField(max_length=255, verbose_name='Course description')),
                ('last_activity', models.DateTimeField(auto_now=True, null=True, verbose_name='Last author’s activity')),
                ('total_score', models.IntegerField(verbose_name='Max score listener can get')),
                ('total_tasks', models.IntegerField(verbose_name='Number of tasks in course')),
                ('unchangeable', models.BooleanField(verbose_name='Course changeable?')),
                ('include_weekly_report', models.BooleanField(verbose_name='Course statistics will be included in the weekly report')),
                ('content_type', models.IntegerField(verbose_name='Course content type')),
            ],
        ),
    ]
