# Generated by Django 2.2.16 on 2022-08-30 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20220829_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseprofile',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Course description'),
        ),
    ]
