# Generated by Django 2.2.16 on 2022-08-30 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20220830_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseprofile',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Course name'),
        ),
    ]
